### ISSUE TITLE
can not use mysql

### ISSUE THREAD

**Issue by wuzhonglin** [luckyframework/avram#113] opened 2019-06-22 12:55 UTC
I used lucky to init a project, and then try to use mysql.
I add it in shard.yml, and add below in .env:

`
DATABASE_URL=mysql://test:test@localhost:3306/test1
`

when I tried ./script/setup
it said such error:

>▸ Setting up the database
Unhandled exception: createdb: could not connect to database template1: received invalid response to SSL negotiation: j
 (Exception)
  from lib/avram/src/avram/tasks/db/create.cr:7:11 in 'call'
  from lib/avram/src/avram/tasks/db/create.cr:1:1 in 'print_help_or_call'
  from lib/lucky_cli/src/lucky_cli/runner.cr:27:9 in 'run'
  from tasks.cr:13:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
>
>▸ Migrating the database
Unhandled exception: Unexpected error while running migrations: no driver was registered for the schema "mysql", did you maybe forget to require the database driver? (Exception)
  from lib/avram/src/avram/tasks/db/migrate.cr:7:11 in 'call'
  from lib/avram/src/avram/tasks/db/migrate.cr:3:1 in 'print_help_or_call'
  from lib/lucky_cli/src/lucky_cli/runner.cr:27:9 in 'run'
  from tasks.cr:13:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???

then I deleted the sentence in .env, and tried to use export

`export DATABASE_URL=mysql://test:test@127.0.0.1:3306/test1
./script/setup
`

it still in error:

All I saw the sample is about postgresql., how about the mysql support?

Environment:
crystal: 0.29.0
lucky: 0.15.0

**Comment by jwoertink** [comment] 2019-06-24 15:02
Hey @wuzhonglin thanks for trying out Lucky! Avram actually doesn't support MySQL by design. It's intended to only support PostgreSQL. You can use MySQL directly with https://github.com/crystal-lang/crystal-mysql, but it requires a little setup in Lucky. We should have some docs on how to do stuff like that sometime soon. 

I'm gonna close this out, but feel free to come hope on [the chat ](https://gitter.im/luckyframework/Lobby) if you have any more questions on how to set that up.

**Closed by jwoertink** 2019-06-24 15:02 UTC

**Comment by jwoertink** [comment] 2019-06-24 15:32
Oh, this is the docs on that https://www.luckyframework.org/guides/database/intro-to-avram-and-orms#alternate-orms
