### ISSUE TITLE
Consistency in migrations between add / remove

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#321] opened 2020-03-16 17:09 UTC
When we run `alter` we have to use this syntax:

```crystal
alter table_for(Whatever) do
  add new_column : String
  remove :old_column
end
```

In `remove`, we have to pass a symbol, but for `add` we can just pass the name. If you pass the column name to `remove`, you'll get the undefined method error.

**Comment by paulcsmith** [comment] 2020-03-16 17:13
> If you pass the column name to remove, you'll get the undefined method error.

Could you clarify this part? I'm not sure I understand

**Comment by jwoertink** [comment] 2020-03-16 17:15
```crystal
  def migrate
    alter table_for(User) do
      add name : String, fill_existing_with: "anonymous"
    end
  end

  def rollback
    alter table_for(User) do
     # This fails with undefined method `name`
      remove name
    end
  end
```

**Comment by paulcsmith** [comment] 2020-03-16 17:23
Oh I see! Gotcha 👍 I agree that should work or at least raise a better error. I'm leaning toward "one way" and raising if not given a symbol. What do you think? I think the bare name is good in macros at the class level but inside other methods I think it's weird and makes it look like it is calling a method

**Comment by jwoertink** [comment] 2020-03-16 17:29
Yeah, I guess that makes sense. If you're in the class space, it's fine, but in the method space it's a little weird. I definitely think it should all be the same for all of them. Less guessing. though..... hold up...

`add :name : String` looks weird... 🤔

**Comment by paulcsmith** [comment] 2020-03-16 17:33
Oh yeah for add I think the type declaration is the way to go. But for remove it doesn't make sense since it doesn't matter what the type is. It is a little weird but probably the most clear since if you did `remove name : Int32` it would work and would be super weird haha.

I'm leaning toward symbol in `remove`, and raise compile error with help text if given something else. That way if you do use it "wrong" it'll point you in the right direction. What do you thin?k

**Comment by jwoertink** [comment] 2020-03-16 17:37
I'm not a big fan on the guessing game (i.e. when is it symbol, when is it not?). Looking at the [guides](https://luckyframework.org/guides/database/migrations#using-fill_existing_with-and-default-values) it looks like we intermix them. 

I guess it looks like the rule is if you pass a type declaration, then no symbol, and if you don't pass a type declaration, then you do pass a symbol...  I can get behind that as long as we raise some nice errors if you do the opposite, and then document on the guides. I like what @edwardloveall says with the element of least surprise.

**Comment by edwardloveall** [comment] 2020-03-16 17:44
How bout `remove name`?

**Comment by paulcsmith** [comment] 2020-03-16 17:52
@edwardloveall Definitely possible but here were my thoughts

> I think the bare name is good in macros at the class level but inside other methods I think it's weird and makes it look like it is calling a method

@jwoertink Agreed. Personally I would *always* use symbols because I think it is weird to have bare names that don't actually call methods. The problem is Crystal itself does not do this. You can do `getter :name` or `getter name` :( 

And so if we force using a Symbol even in macros at the class level we're going against Crystal and violating least surprise since you can do this with most other macros in Crystal.

So I dunno. It is tricky. My personal preference is:

* Class level macros no symbol (but allow symbol to match Crystal class level macros
* If used inside methods use a symbol

Crystal has very few (maybe zero?) macros you use inside methods. I think in general `remove` should just be treated as a regular method and therefore needs a symbol. You shouldn't even have to know it can accept a bare name.

Also, I think we may be able to just make `remove` a regular method!

**Comment by jwoertink** [comment] 2020-03-16 17:56
Yeah, I like using this as the rule:

> if you pass a type declaration, then no symbol, and if you don't pass a type declaration, then you do pass a symbol

It's a little confusing, but easy to set as a hard rule that we can document and just keep consistent on.

**Comment by paulcsmith** [comment] 2020-03-16 18:45
Hmm I'm a bit confused. I just went to fix this and it looks like we cover this already. The method only allows symbols and remove_belongs_to also raises a helpful error. Maybe this was on an older version of Avram?

https://github.com/luckyframework/avram/blob/98088a2794a7ac7df3e9d822bc15fae7f6c24d25/src/avram/migrator/alter_table_statement.cr#L168-L177

**Comment by jwoertink** [comment] 2020-03-16 20:01
I ran that from a brand new fresh generated app.

**Comment by paulcsmith** [comment] 2020-03-16 20:07
Ohhhhh, ok I get it now. It's because it is a method that it fails.

It tries to call `name` since it is not a macro. The only way around this would be to actually make `remove` macro so that we can raise if given a bare name like that...it's a bit of a weird case but maybe is worth making into a macro to raise a helpful error for users?

**Comment by jwoertink** [comment] 2020-03-16 20:16
That sounds fine. We could also just close this and then just open a new issue to better document on the guides of why one way over the other and such. I'm cool with either

**Comment by wout** [comment] 2020-05-12 12:15
Shall I pick this up and make it into a macro, with an error message similar to `add_belongs_to`?

**Comment by paulcsmith** [comment] 2020-05-12 17:18
@wout That'd be great!

**Comment by wout** [comment] 2020-05-12 18:24
Brilliant. Coming up. :smile:

**Comment by paulcsmith** [comment] 2020-05-13 15:41
Closed by https://github.com/luckyframework/avram/pull/366

**Closed** 2020-05-13 15:42 UTC
Labels: clarify api
